name: Build and Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: demorgacr.azurecr.io
  IMAGE_NAME: webapp
  CLUSTER_NAME: demo-aks-cluster
  RESOURCE_GROUP: demo-aks-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # ✅ Build and push the image from correct path
      - name: Build and push Docker image
        run: |
          docker build -t $REGISTR
